const mockOrders = [
  {
    id: "1",
    product: {
      name: "Green Tea Premium",
      image: "/green-tea-product.jpg",
    },
    orderId: "7712309",
    price: 1452.5,
    quantity: 1638,
    payment: 20,
    status: "Success",
    tracking: "Tracking",
  },
  {
    id: "2",
    product: {
      name: "Organic Cereal Box",
      image: "/cereal-box-product.jpg",
    },
    orderId: "7712310",
    price: 892.75,
    quantity: 842,
    payment: 15,
    status: "Pending",
    tracking: "Tracking",
  },
  {
    id: "3",
    product: {
      name: "Purple Snack Pack",
      image: "/purple-snack-product.jpg",
    },
    orderId: "712311",
    price: 1452.5,
    quantity: 1638,
    payment: 20,
    status: "Success",
    tracking: "Tracking",
  },
  {
    id: "4",
    product: {
      name: "Red Energy Beverage",
      image: "/red-beverage-product.jpg",
    },
    orderId: "7712312",
    price: 2100.0,
    quantity: 2450,
    payment: 35,
    status: "Success",
    tracking: "Tracking",
  },
  {
    id: "5",
    product: {
      name: "Artisanal Coffee Beans",
      image: "/artisanal-coffee-beans.png",
    },
    orderId: "77123712313",
    price: 675.25,
    quantity: 520,
    payment: 12,
    status: "Cancel",
    tracking: "Tracking",
  },
  {
    id: "6",
    product: {
      name: "Chocolate Protein Bar",
      image: "/green-tea-product.jpg",
    },
    orderId: "7712314",
    price: 345.0,
    quantity: 890,
    payment: 8,
    status: "Success",
    tracking: "Tracking",
  },
  {
    id: "7",
    product: {
      name: "Vitamin Water Pack",
      image: "/cereal-box-product.jpg",
    },
    orderId: "7712315",
    price: 1890.5,
    quantity: 1200,
    payment: 25,
    status: "Pending",
    tracking: "Tracking",
  },
  {
    id: "8",
    product: {
      name: "Granola Mix Deluxe",
      image: "/purple-snack-product.jpg",
    },
    orderId: "#7712316",
    price: 567.8,
    quantity: 675,
    payment: 10,
    status: "Success",
    tracking: "Tracking",
  },
  {
    id: "9",
    product: {
      name: "Herbal Tea Collection",
      image: "/red-beverage-product.jpg",
    },
    orderId: "#7712317",
    price: 1234.0,
    quantity: 980,
    payment: 18,
    status: "Cancel",
    tracking: "Tracking",
  },
  {
    id: "10",
    product: {
      name: "Protein Shake Mix",
      image: "/artisanal-coffee-beans.png",
    },
    orderId: "#7712318",
    price: 2345.75,
    quantity: 1850,
    payment: 40,
    status: "Success",
    tracking: "Tracking",
  },
  {
    id: "11",
    product: {
      name: "Organic Honey Jar",
      image: "/green-tea-product.jpg",
    },
    orderId: "#7712319",
    price: 456.5,
    quantity: 430,
    payment: 9,
    status: "Pending",
    tracking: "Tracking",
  },
  {
    id: "12",
    product: {
      name: "Almond Butter Spread",
      image: "/cereal-box-product.jpg",
    },
    orderId: "#7712320",
    price: 789.0,
    quantity: 620,
    payment: 14,
    status: "Success",
    tracking: "Tracking",
  },
];

export { mockOrders };
