import { Manrope } from 'next/font/google';
import './globals.css';

import Navbar from '@/components/nav/navbar';
import Footer from '@/components/footer/footer';

import ReduxProvider from '@/redux/Provider';

// If loading a variable font, you don't need to specify the font weight


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={`   antialiased`}>
        <Navbar></Navbar>
        <ReduxProvider>
         
        {children}
        <footer>
          <Footer></Footer>
        </footer>
       </ReduxProvider>
      </body>
    </html>
  );
}
