import { Manrope } from 'next/font/google';
import './globals.css';

import Navbar from '@/components/nav/navbar';
import Footer from '@/components/footer/footer';
// If loading a variable font, you don't need to specify the font weight
const ManropeFont = Manrope({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ManropeFont.className}  antialiased`}>
        <Navbar></Navbar>
        {children}
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
